//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\UGII\application\TechDoc.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: admin
//              Version: NX 9
//              Date: 09-15-2015  (Format: mm-dd-yyyy)
//              Time: 16:52 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C# source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
using System;
using System.Diagnostics;
using NXOpen;
using NXOpen.BlockStyler;

//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
public class TechDoc
{
    //class members
    public static Session theSession = null;
    public static UI theUI = null;
    private string theDlxFileName;
    private NXOpen.BlockStyler.BlockDialog theDialog;
    private NXOpen.BlockStyler.TabControl tabControl;// Block type: Tabs Page
    private NXOpen.BlockStyler.Group tabPage;// Block type: Group
    private NXOpen.BlockStyler.Group group5;// Block type: Group
    public NXOpen.BlockStyler.StringBlock string0;// Block type: String
    public NXOpen.BlockStyler.StringBlock string01;// Block type: String
    public NXOpen.BlockStyler.Enumeration enum0;// Block type: Enumeration
    private NXOpen.BlockStyler.Separator separator0;// Block type: Separator
    public NXOpen.BlockStyler.Enumeration enum01;// Block type: Enumeration
    public NXOpen.BlockStyler.StringBlock string02;// Block type: String
    private NXOpen.BlockStyler.Separator separator01;// Block type: Separator
    public NXOpen.BlockStyler.Enumeration enum02;// Block type: Enumeration
    public NXOpen.BlockStyler.StringBlock string03;// Block type: String
    private NXOpen.BlockStyler.Separator separator02;// Block type: Separator
    public NXOpen.BlockStyler.Enumeration enum03;// Block type: Enumeration
    public NXOpen.BlockStyler.StringBlock string04;// Block type: String
    private NXOpen.BlockStyler.Separator separator03;// Block type: Separator
    public NXOpen.BlockStyler.Enumeration enum04;// Block type: Enumeration
    public NXOpen.BlockStyler.StringBlock string05;// Block type: String
    private NXOpen.BlockStyler.Separator separator04;// Block type: Separator
    public NXOpen.BlockStyler.StringBlock string06;// Block type: String
    private NXOpen.BlockStyler.Button button0;// Block type: Button
    private NXOpen.BlockStyler.Button button01;// Block type: Button
    private NXOpen.BlockStyler.Group tabPage1;// Block type: Group
    private NXOpen.BlockStyler.Group group;// Block type: Group
    public NXOpen.BlockStyler.IntegerBlock integer0;// Block type: Integer
    private NXOpen.BlockStyler.IntegerBlock integer01;// Block type: Integer
    private NXOpen.BlockStyler.Separator separator06;// Block type: Separator
    public NXOpen.BlockStyler.Enumeration enum05;// Block type: Enumeration
    public NXOpen.BlockStyler.Enumeration enum06;// Block type: Enumeration
    public NXOpen.BlockStyler.Group group1;// Block type: Group
    public NXOpen.BlockStyler.Toggle toggle0;// Block type: Toggle
    private NXOpen.BlockStyler.Separator separator07;// Block type: Separator
    public NXOpen.BlockStyler.Enumeration enum07;// Block type: Enumeration
    private NXOpen.BlockStyler.IntegerBlock integer02;// Block type: Integer
    private NXOpen.BlockStyler.Separator separator08;// Block type: Separator
    private NXOpen.BlockStyler.Button button02;// Block type: Button
    public NXOpen.BlockStyler.Group group2;// Block type: Group
    public NXOpen.BlockStyler.Toggle toggle01;// Block type: Toggle
    private NXOpen.BlockStyler.Separator separator09;// Block type: Separator
    public NXOpen.BlockStyler.Enumeration enum09;// Block type: Enumeration
    private NXOpen.BlockStyler.IntegerBlock integer021;// Block type: Integer
    private NXOpen.BlockStyler.Separator separator010;// Block type: Separator
    private NXOpen.BlockStyler.Button button03;// Block type: Button
    public NXOpen.BlockStyler.Group group3;// Block type: Group
    public NXOpen.BlockStyler.Toggle toggle02;// Block type: Toggle
    public NXOpen.BlockStyler.Enumeration enum011;// Block type: Enumeration
    private NXOpen.BlockStyler.IntegerBlock integer022;// Block type: Integer
    private NXOpen.BlockStyler.Separator separator011;// Block type: Separator
    private NXOpen.BlockStyler.Button button04;// Block type: Button
    private NXOpen.BlockStyler.Button button05;// Block type: Button
    private NXOpen.BlockStyler.Group tabPage2;// Block type: Group
    private NXOpen.BlockStyler.Group group4;// Block type: Group
    private NXOpen.BlockStyler.Toggle toggle03;// Block type: Toggle
    private NXOpen.BlockStyler.Button button06;// Block type: Button
    private DataService _dataService;

    //------------------------------------------------------------------------------
    //Constructor for NX Styler class
    //------------------------------------------------------------------------------
    public TechDoc()
    {
        try
        {
            theSession = Session.GetSession();
            theUI = UI.GetUI();
            theDlxFileName = "TechDoc.dlx";
            theDialog = theUI.CreateDialog(theDlxFileName);
            theDialog.AddApplyHandler(new NXOpen.BlockStyler.BlockDialog.Apply(apply_cb));
            theDialog.AddOkHandler(new NXOpen.BlockStyler.BlockDialog.Ok(ok_cb));
            theDialog.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
            theDialog.AddCancelHandler(new NXOpen.BlockStyler.BlockDialog.Cancel(cancel_cb));
            theDialog.AddFilterHandler(new NXOpen.BlockStyler.BlockDialog.Filter(filter_cb));
            theDialog.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
            theDialog.AddFocusNotifyHandler(new NXOpen.BlockStyler.BlockDialog.FocusNotify(focusNotify_cb));
            theDialog.AddKeyboardFocusNotifyHandler(new NXOpen.BlockStyler.BlockDialog.KeyboardFocusNotify(keyboardFocusNotify_cb));
            theDialog.AddEnableOKButtonHandler(new NXOpen.BlockStyler.BlockDialog.EnableOKButton(enableOKButton_cb));
            theDialog.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            throw ex;
        }
    }
    //------------------------------- DIALOG LAUNCHING ---------------------------------
    //
    //    Before invoking this application one needs to open any part/empty part in NX
    //    because of the behavior of the blocks.
    //
    //    Make sure the dlx file is in one of the following locations:
    //        1.) From where NX session is launched
    //        2.) $UGII_USER_DIR/application
    //        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    //            recommended. This variable is set to a full directory path to a file 
    //            containing a list of root directories for all custom applications.
    //            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_ROOT_DIR\menus\custom_dirs.dat
    //
    //    You can create the dialog using one of the following way:
    //
    //    1. Journal Replay
    //
    //        1) Replay this file through Tool->Journal->Play Menu.
    //
    //    2. USER EXIT
    //
    //        1) Remove the following conditional definitions:
    //                a) #if USER_EXIT_OR_MENU
    //                    #endif//USER_EXIT_OR_MENU
    //
    //                b) #if USER_EXIT
    //                    #endif//USER_EXIT
    //        2) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
    //        3) Invoke the Shared Library through File->Execute->NX Open menu.
    //
    //    3. THROUGH CALLBACK OF ANOTHER DIALOG
    //
    //        1) Remove the following conditional definition:
    //             #if CALLBACK
    //             #endif//CALLBACK
    //        2) Call the following line of code from where ever you want to lauch this dialog.
    //             TechDoc.Show_TechDoc();
    //        3) Integrate this file with your main application file.
    //
    //    4. MENU BAR
    //    
    //        1) Remove the following conditional definition:
    //                a) #if USER_EXIT_OR_MENU
    //                   #endif//USER_EXIT_OR_MENU
    //        2) Add the following lines to your MenuScript file in order to
    //           associate a menu bar button with your dialog.  In this
    //           example, a cascade menu will be created and will be
    //           located just before the Help button on the main menubar.
    //           The button, SAMPLEVB_BTN is set up to launch your dialog and
    //           will be positioned as the first button on your pulldown menu.
    //           If you wish to add the button to an existing cascade, simply
    //           add the 3 lines between MENU LAUNCH_CASCADE and END_OF_MENU
    //           to your menuscript file.
    //           The MenuScript file requires an extension of ".men".
    //           Move the contents between the dashed lines to your Menuscript file.
    //        
    //           !-----------------------------------------------------------------------------
    //           VERSION 120
    //        
    //           EDIT UG_GATEWAY_MAIN_MENUBAR
    //        
    //           BEFORE UG_HELP
    //           CASCADE_BUTTON BLOCKSTYLER_DLX_CASCADE_BTN
    //           LABEL Dialog Launcher
    //           END_OF_BEFORE
    //        
    //           MENU BLOCKSTYLER_DLX_CASCADE_BTN
    //           BUTTON SAMPLEVB_BTN
    //           LABEL Display SampleVB dialog
    //           ACTIONS <path of Shared library> !For example: D:\temp\SampleVB.dll
    //           END_OF_MENU
    //           !-----------------------------------------------------------------------------
    //        
    //        3) Make sure the .men file is in one of the following locations:
    //        
    //           - $UGII_USER_DIR/startup   
    //           - For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    //             recommended. This variable is set to a full directory path to a file 
    //             containing a list of root directories for all custom applications.
    //             e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_ROOT_DIR\menus\custom_dirs.dat
    //    
    //------------------------------------------------------------------------------

    public static void Main()
    {
        TechDoc theTechDoc = null;
        try
        {
            theTechDoc = new TechDoc();
            theTechDoc._dataService = new DataService(theTechDoc);
            // The following method shows the dialog immediately
            theTechDoc.Show();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        finally
        {
            if(theTechDoc != null)
                theTechDoc.Dispose();
                theTechDoc = null;
        }
    }

//#if USER_EXIT
    //------------------------------------------------------------------------------
    // This method specifies how a shared image is unloaded from memory
    // within NX. This method gives you the capability to unload an
    // internal NX Open application or user  exit from NX. Specify any
    // one of the three constants as a return value to determine the type
    // of unload to perform:
    //
    //
    //    Immediately : unload the library as soon as the automation program has completed
    //    Explicitly  : unload the library from the "Unload Shared Image" dialog
    //    AtTermination : unload the library when the NX session terminates
    //
    //
    // NOTE:  A program which associates NX Open applications with the menubar
    // MUST NOT use this option since it will UNLOAD your NX Open application image
    // from the menubar.
    //------------------------------------------------------------------------------
     public static int GetUnloadOption(string arg)
    {
        //return System.Convert.ToInt32(Session.LibraryUnloadOption.Explicitly);
         return System.Convert.ToInt32(Session.LibraryUnloadOption.Immediately);
        // return System.Convert.ToInt32(Session.LibraryUnloadOption.AtTermination);
    }
    
    //------------------------------------------------------------------------------
    // Following method cleanup any housekeeping chores that may be needed.
    // This method is automatically called by NX.
    //------------------------------------------------------------------------------
    public static void UnloadLibrary(string arg)
    {
        try
        {
            //---- Enter your code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
//#endif//USER_EXIT
    
    //------------------------------------------------------------------------------
    //This method shows the dialog on the screen
    //------------------------------------------------------------------------------
    public NXOpen.UIStyler.DialogResponse Show()
    {
        try
        {
            theDialog.Show();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }
    
    //------------------------------------------------------------------------------
    //Method Name: Dispose
    //------------------------------------------------------------------------------
    public void Dispose()
    {
        if(theDialog != null)
        {
            _dataService = null;
            theDialog.Dispose();
            theDialog = null;
        }
    }
    
#if CALLBACK
    //------------------------------------------------------------------------------
    //Method name: Show_TechDoc
    //------------------------------------------------------------------------------
    public static void Show_TechDoc()
    {
        TechDoc theTechDoc = null;
        try
        {
            theTechDoc = new TechDoc();
            // The following method shows the dialog immediately
            theTechDoc.Show();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        finally
        {
            theTechDoc.Dispose();
            theTechDoc = null;
        }
    }
#endif//CALLBACK
    
    //------------------------------------------------------------------------------
    //---------------------Block UI Styler Callback Functions--------------------------
    //------------------------------------------------------------------------------
    
    //------------------------------------------------------------------------------
    //Callback Name: initialize_cb
    //------------------------------------------------------------------------------
    public void initialize_cb()
    {
        try
        {
            tabControl = (NXOpen.BlockStyler.TabControl)theDialog.TopBlock.FindBlock("tabControl");
            tabPage = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("tabPage");
            group5 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group5");
            string0 = (NXOpen.BlockStyler.StringBlock)theDialog.TopBlock.FindBlock("string0");
            string01 = (NXOpen.BlockStyler.StringBlock)theDialog.TopBlock.FindBlock("string01");
            enum0 = (NXOpen.BlockStyler.Enumeration)theDialog.TopBlock.FindBlock("enum0");
            separator0 = (NXOpen.BlockStyler.Separator)theDialog.TopBlock.FindBlock("separator0");
            enum01 = (NXOpen.BlockStyler.Enumeration)theDialog.TopBlock.FindBlock("enum01");
            string02 = (NXOpen.BlockStyler.StringBlock)theDialog.TopBlock.FindBlock("string02");
            separator01 = (NXOpen.BlockStyler.Separator)theDialog.TopBlock.FindBlock("separator01");
            enum02 = (NXOpen.BlockStyler.Enumeration)theDialog.TopBlock.FindBlock("enum02");
            string03 = (NXOpen.BlockStyler.StringBlock)theDialog.TopBlock.FindBlock("string03");
            separator02 = (NXOpen.BlockStyler.Separator)theDialog.TopBlock.FindBlock("separator02");
            enum03 = (NXOpen.BlockStyler.Enumeration)theDialog.TopBlock.FindBlock("enum03");
            string04 = (NXOpen.BlockStyler.StringBlock)theDialog.TopBlock.FindBlock("string04");
            separator03 = (NXOpen.BlockStyler.Separator)theDialog.TopBlock.FindBlock("separator03");
            enum04 = (NXOpen.BlockStyler.Enumeration)theDialog.TopBlock.FindBlock("enum04");
            string05 = (NXOpen.BlockStyler.StringBlock)theDialog.TopBlock.FindBlock("string05");
            separator04 = (NXOpen.BlockStyler.Separator)theDialog.TopBlock.FindBlock("separator04");
            string06 = (NXOpen.BlockStyler.StringBlock)theDialog.TopBlock.FindBlock("string06");
            button0 = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("button0");
            button01 = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("button01");
            tabPage1 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("tabPage1");
            group = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group");
            integer0 = (NXOpen.BlockStyler.IntegerBlock)theDialog.TopBlock.FindBlock("integer0");
            integer01 = (NXOpen.BlockStyler.IntegerBlock)theDialog.TopBlock.FindBlock("integer01");
            separator06 = (NXOpen.BlockStyler.Separator)theDialog.TopBlock.FindBlock("separator06");
            enum05 = (NXOpen.BlockStyler.Enumeration)theDialog.TopBlock.FindBlock("enum05");
            enum06 = (NXOpen.BlockStyler.Enumeration)theDialog.TopBlock.FindBlock("enum06");
            group1 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group1");
            toggle0 = (NXOpen.BlockStyler.Toggle)theDialog.TopBlock.FindBlock("toggle0");
            separator07 = (NXOpen.BlockStyler.Separator)theDialog.TopBlock.FindBlock("separator07");
            enum07 = (NXOpen.BlockStyler.Enumeration)theDialog.TopBlock.FindBlock("enum07");
            integer02 = (NXOpen.BlockStyler.IntegerBlock)theDialog.TopBlock.FindBlock("integer02");
            separator08 = (NXOpen.BlockStyler.Separator)theDialog.TopBlock.FindBlock("separator08");
            button02 = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("button02");
            group2 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group2");
            toggle01 = (NXOpen.BlockStyler.Toggle)theDialog.TopBlock.FindBlock("toggle01");
            separator09 = (NXOpen.BlockStyler.Separator)theDialog.TopBlock.FindBlock("separator09");
            enum09 = (NXOpen.BlockStyler.Enumeration)theDialog.TopBlock.FindBlock("enum09");
            integer021 = (NXOpen.BlockStyler.IntegerBlock)theDialog.TopBlock.FindBlock("integer021");
            separator010 = (NXOpen.BlockStyler.Separator)theDialog.TopBlock.FindBlock("separator010");
            button03 = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("button03");
            group3 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group3");
            toggle02 = (NXOpen.BlockStyler.Toggle)theDialog.TopBlock.FindBlock("toggle02");
            enum011 = (NXOpen.BlockStyler.Enumeration)theDialog.TopBlock.FindBlock("enum011");
            integer022 = (NXOpen.BlockStyler.IntegerBlock)theDialog.TopBlock.FindBlock("integer022");
            separator011 = (NXOpen.BlockStyler.Separator)theDialog.TopBlock.FindBlock("separator011");
            button04 = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("button04");
            button05 = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("button05");
            tabPage2 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("tabPage2");
            group4 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group4");
            toggle03 = (NXOpen.BlockStyler.Toggle)theDialog.TopBlock.FindBlock("toggle03");
            button06 = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("button06");
            
            _dataService.initialize_AttributeDataBinding();
            _dataService.initialize_DrawingsDataBinding();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: dialogShown_cb
    //This callback is executed just before the dialog launch. Thus any value set 
    //here will take precedence and dialog will be launched showing that value. 
    //------------------------------------------------------------------------------
    public void dialogShown_cb()
    {
        try
        {
            //---- Enter your callback code here -----
            _dataService.update_DrawingsDataBinding();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: apply_cb
    //------------------------------------------------------------------------------
    public int apply_cb()
    {
        int errorCode = 0;
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: update_cb
    //------------------------------------------------------------------------------
    public int update_cb( NXOpen.BlockStyler.UIBlock block)
    {
        try
        {
            _dataService.update_cb(block);

            if(block == string0)
            {
            //---------Enter your code here-----------
            }
            else if(block == string01)
            {
            //---------Enter your code here-----------
            }
            else if(block == enum0)
            {
            //---------Enter your code here-----------
            }
            else if(block == separator0)
            {
            //---------Enter your code here-----------
            }
            else if(block == enum01)
            {
            //---------Enter your code here-----------
            }
            else if(block == string02)
            {
            //---------Enter your code here-----------
            }
            else if(block == separator01)
            {
            //---------Enter your code here-----------
            }
            else if(block == enum02)
            {
            //---------Enter your code here-----------
            }
            else if(block == string03)
            {
            //---------Enter your code here-----------
            }
            else if(block == separator02)
            {
            //---------Enter your code here-----------
            }
            else if(block == enum03)
            {
            //---------Enter your code here-----------
            }
            else if(block == string04)
            {
            //---------Enter your code here-----------
            }
            else if(block == separator03)
            {
            //---------Enter your code here-----------
            }
            else if(block == enum04)
            {
            //---------Enter your code here-----------
            }
            else if(block == string05)
            {
            //---------Enter your code here-----------
            }
            else if(block == separator04)
            {
            //---------Enter your code here-----------
            }
            else if(block == string06)
            {
            //---------Enter your code here-----------
            }
            else if(block == button0)
            {
            //---------Enter your code here-----------
            }
            else if(block == button01)
            {
            //---------Enter your code here-----------
            }
            else if(block == integer0)
            {
            //---------Enter your code here-----------
            }
            else if(block == integer01)
            {
            //---------Enter your code here-----------
            }
            else if(block == separator06)
            {
            //---------Enter your code here-----------
            }
            else if(block == enum05)
            {
            //---------Enter your code here-----------
            }
            else if(block == enum06)
            {
            //---------Enter your code here-----------
            }
            else if(block == toggle0)
            {
            //---------Enter your code here-----------
            }
            else if(block == separator07)
            {
            //---------Enter your code here-----------
            }
            else if(block == enum07)
            {
            //---------Enter your code here-----------
            }
            else if(block == integer02)
            {
            //---------Enter your code here-----------
            }
            else if(block == separator08)
            {
            //---------Enter your code here-----------
            }
            else if(block == button02)
            {
            //---------Enter your code here-----------
            }
            else if(block == toggle01)
            {
            //---------Enter your code here-----------
            }
            else if(block == separator09)
            {
            //---------Enter your code here-----------
            }
            else if(block == enum09)
            {
            //---------Enter your code here-----------
            }
            else if(block == integer021)
            {
            //---------Enter your code here-----------
            }
            else if(block == separator010)
            {
            //---------Enter your code here-----------
            }
            else if(block == button03)
            {
            //---------Enter your code here-----------
            }
            else if(block == toggle02)
            {
            //---------Enter your code here-----------
            }
            else if(block == enum011)
            {
            //---------Enter your code here-----------
            }
            else if(block == integer022)
            {
            //---------Enter your code here-----------
            }
            else if(block == separator011)
            {
            //---------Enter your code here-----------
            }
            else if(block == button04)
            {
            //---------Enter your code here-----------
            }
            else if(block == button05)
            {
            //---------Enter your code here-----------
            }
            else if(block == toggle03)
            {
            //---------Enter your code here-----------
            }
            else if(block == button06)
            {
            //---------Enter your code here-----------
            }
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: ok_cb
    //------------------------------------------------------------------------------
    public int ok_cb()
    {
        int errorCode = 0;
        try
        {
            errorCode = apply_cb();
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: cancel_cb
    //------------------------------------------------------------------------------
    public int cancel_cb()
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: filter_cb
    //------------------------------------------------------------------------------
    public int filter_cb(NXOpen.BlockStyler.UIBlock block, NXOpen.TaggedObject selectedObject)
    {
        return(NXOpen.UF.UFConstants.UF_UI_SEL_ACCEPT);
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: focusNotify_cb
    //This callback is executed when any block (except the ones which receive keyboard entry such as Integer block) receives focus.
    //------------------------------------------------------------------------------
    public void focusNotify_cb(NXOpen.BlockStyler.UIBlock block, bool focus)
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: keyboardFocusNotify_cb
    //This callback is executed when block which can receive keyboard entry, receives the focus.
    //------------------------------------------------------------------------------
    public void keyboardFocusNotify_cb(NXOpen.BlockStyler.UIBlock block, bool focus)
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: enableOKButton_cb
    //This callback allows the dialog to enable/disable the OK and Apply button.
    //------------------------------------------------------------------------------
    public bool enableOKButton_cb()
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return true;
    }
    
    //------------------------------------------------------------------------------
    //Function Name: GetBlockProperties
    //Returns the propertylist of the specified BlockID
    //------------------------------------------------------------------------------
    public PropertyList GetBlockProperties(string blockID)
    {
        PropertyList plist =null;
        try
        {
            plist = theDialog.GetBlockProperties(blockID);
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return plist;
    }
    
}
